server:
  port: 8082 # Порт, на котором будет работать Gateway

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user_crud_route # Уникальный ID маршрута

#          uri: http://localhost:8080
          uri: http://app:8080
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=0
            - AddRequestHeader=X-Gateway-Request, true
logging: # Добавьте этот блок для подробного логирования
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG # Может быть полезно для отладки HTTP-запросов к бэкенду
